### ISSUE TITLE
Make concourse web run in it's own user.

### ISSUE THREAD

**Issue by fuel-wlightning** [motevets/concourse-in-a-box#3]
I'd like to see the concourse web process run under a specific user, rather than the current one (that has sudo capabilities).

**Comment by kindrowboat** [comment]
Would you envision this being added as an argument?  Would running `sudo -u OTHER_USER ciab` be sufficient?

**Comment by fuel-wlightning** [comment]
I don't think so, you'd have to run setup as the same user, since it needs access to the keys.

I was thinking of extending setup.bash to create a "concourse" user on the system, then adding that user to postgresql. This would make #4 a little more realisitic, since the init script is going to need to know the proper users to run everything as.

Currently, the web process actually runs as root since you're sudo'ing the ciab script. If you ran ciab without sudo, then it would start as the current user.

**Comment by kindrowboat** [comment]
I think this is a reasonable change.
