### ISSUE TITLE
Install fly client

### ISSUE THREAD

**Issue by fuel-wlightning** [motevets/concourse-in-a-box#5]
It'd be nice to have the fly client installed with the setup script.

Not sure how doable this is, as it seems that you have to run web in order to download the client.

**Comment by kindrowboat** [comment]
What would be the motivation for this?  Are you planning on developing the pipeline on the same machine that running concourse?

**Comment by fuel-wlightning** [comment]
This would make it possible to trial concourse completely without installing extra tools to a local machine. For instance, combined with a Vagrantfile, this would allow someone to quickly spin up a throwaway instance to try out Concourse.

**Comment by kindrowboat** [comment]
I'm not sure it would be in the scope of this project to download the fly cli as part of the setup; however, as part of your Vagrant provisioning, could you run the following after `setup.sh`?

``` bash
wget http://IP_ADDR:8080/api/v1/cli?arch=amd64&platform=linux
sudo install -m 755 fly /usr/local/bin
```

**Comment by fuel-wlightning** [comment]
It would have to be after ciab script, setup.bash doesn't start the concourse web server.

**Comment by kindrowboat** [comment]
Yeah, you're right. I still don't think we should add it to the setup script. It's not the typical use-case to have the fly CLI on the machine(s) running Concourse.

Also were you aware that there's already a concourse-lite Vagrant box?

**Comment by fuel-wlightning** [comment]
Yeah, unfortunately it only works only with VirtualBox, and isn't setup with provisioners, it comes pre-baked into the box image. Also, when I checked it didn't have the latest release.

**Comment by kindrowboat** [comment]
Ah, shame. Well I'll be glad to help with this repo anyway I can; however I'm going to close this issue for the reasons stated above.
